steps:
  # Install
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  # Deploy
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'nodeapp', '--image', 'gcr.io/tenseconds-b5f56/nodeapp', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated']
images:
  - gcr.io/tenseconds-b5f56/nodeapp